// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbRjFUZC-KHPYe_Nezfp_9wbiC93lGAgU',
    appId: '1:299526553902:web:cebff7b6ccebfda821fabf',
    messagingSenderId: '299526553902',
    projectId: 'final-proyect-fef1c',
    authDomain: 'final-proyect-fef1c.firebaseapp.com',
    storageBucket: 'final-proyect-fef1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-M5LivAxKGSnJBKIvKxQCBxvtu9F0s6Q',
    appId: '1:299526553902:android:ab81eb1e0327fde621fabf',
    messagingSenderId: '299526553902',
    projectId: 'final-proyect-fef1c',
    storageBucket: 'final-proyect-fef1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeOLYqy4nfNvsTLtPjrQRxRkkMT0ZNxDM',
    appId: '1:299526553902:ios:9d373c8669de526b21fabf',
    messagingSenderId: '299526553902',
    projectId: 'final-proyect-fef1c',
    storageBucket: 'final-proyect-fef1c.firebasestorage.app',
    iosBundleId: 'com.example.finalProyect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeOLYqy4nfNvsTLtPjrQRxRkkMT0ZNxDM',
    appId: '1:299526553902:ios:9d373c8669de526b21fabf',
    messagingSenderId: '299526553902',
    projectId: 'final-proyect-fef1c',
    storageBucket: 'final-proyect-fef1c.firebasestorage.app',
    iosBundleId: 'com.example.finalProyect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbRjFUZC-KHPYe_Nezfp_9wbiC93lGAgU',
    appId: '1:299526553902:web:a2ec2f0838a566fc21fabf',
    messagingSenderId: '299526553902',
    projectId: 'final-proyect-fef1c',
    authDomain: 'final-proyect-fef1c.firebaseapp.com',
    storageBucket: 'final-proyect-fef1c.firebasestorage.app',
  );
}
